name: prod # no importa si ya existe porque va a ser instalado en un prefijo local

dependencies:
  - pip
  - sqlalchemy
  - pydantic
  - passlib
  - bcrypt
  - numpy
  - jupyter
  - jupyterlab
  - pip:
    - fastapi
    - uvicorn
    - python-multipart
    - pyjwt


# comandos utiles:

# conda env create --prefix ./env -f environment.yml
# conda activate ./env
# conda env update --prefix ./env -f environment.yml --prune
# conda env export --from-history -f environment.yml
